### ISSUE TITLE
Add other standards?

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/phpcs-neutron-standard#13]
This is a question up for debate: should this standard include other standards which we recommend, such as WordPress (which itself contains Squiz and others) and VariableAnalysis?

Personally I think we should not, because it makes the standards too tightly coupled. I think instead we could consider creating a separate repository which was effectively just a ruleset.xml file that included all these standards. This would be similar, in a way, to [babel's presets](https://babeljs.io/docs/plugins/#presets) or an [eslint sharable config](https://eslint.org/docs/developer-guide/shareable-configs).

**Comment by Hywan** [comment]
I agree with the fact we should no add other standards. It's better to explain how to include this ruleset into another one.

**Comment by sirbrillig** [comment]
Created a meta-ruleset here: https://github.com/Automattic/phpcs-neutron-ruleset

To do:
- [x] update README in this repo to refer to the meta repo
