### ISSUE TITLE
RequireStrictTypesSniff.php acts on all open tag and not only on first

### ISSUE THREAD

**Issue by gmazzap** [sirbrillig/phpcs-neutron-standard#18]
`RequireStrictTypesSniff.php` is used to enforce that stricts types are declared.

The problem is it acts on _all_ open tags, and not only on the first , considering `declare` must be the first instruction in a file, checking for the first open tag is good enough for the purpose of the sniff.

The problem with checking all the open tags it will very likely cause false positives in templates.

For example:

```php
<?php
declare( strict_types=1 );

$test = 'test';

?>
<div>
<?php
echo esc_html( $test );
?>
</div>
```

will result in:

```
8 | [ ERROR ] [ ] File must start with a strict types declaration.
```

**Comment by sirbrillig** [comment]
Good point! I've been in files that are entirely business logic lately and forgot that multiple PHP opener tags can exist.
