### ISSUE TITLE
Stricts types declaration should not be checked on interfaces.

### ISSUE THREAD

**Issue by gmazzap** [sirbrillig/phpcs-neutron-standard#20]
In PHP `declare(strict_types=1)` is something that affects functions _calls_ inside a file, not function _declarations_.

From [php.net](http://php.net/manual/en/functions.arguments.php#functions.arguments.type-declaration.strict)

> **Note**:
>Strict typing applies to function calls made from within the file with strict typing enabled, not to the functions declared within that file...

In an interface, for the very nature of PHP interface, there will never be function calls inside an interface, which means that declaring strict types in an interface file is useless. Yes, it is also harmless, but I think marking as error something is not arror is still a bug.

**Comment by sirbrillig** [comment]
🤔  That's a good point. I suppose if the file contains and `interface` definition and no other top-level expressions, then this sniff should ignore it?

**Comment by gmazzap** [comment]
@sirbrillig Yes. I use neutron standard in combination with PSR-2 (and so you do, [it seems](https://github.com/Automattic/phpcs-neutron-standard/blob/master/phpcs.xml#L12)) where a file can only be used to declare one symbol, so if it contains an interface, then it _only_ contains an interface.

But yes, to make this agnostic about other standards, you should check if a file only declares an interface, and if so ignore the stricts types declaration check.

**Comment by Chrico** [comment]
This seems still to fail. @sirbrillig 

When i've following interface:

```php
<?php

namespace Just\For\Testing;

use Brain\Nonces\NonceInterface;

/**
 * Interface SettingsPageAuthInterface
 */
interface SettingsPageAuthInterface
{

    /**
     * @param array $request_data
     *
     * @return bool
     */
    public function isAllowed(array $request_data = []): bool;

    /**
     * @return NonceInterface
     */
    public function nonce(): NonceInterface;

    /**
     * @return string
     */
    public function cap(): string;
}

```

I am seeing:

```
1 | ERROR | File must start with a strict types declaration
 1 | ERROR | An error occurred during processing; checking has been aborted. The error message was: Undefined index: bracket_closer in
   |       | {xxxxxx}\vendor\automattic\phpcs-neutron-standard\NeutronStandard\Sniffs\Functions\TypeHintSniff.php on line 46

```

**Comment by sirbrillig** [comment]
Thanks for noticing and for the example, @Chrico! 🤔  Looks like there's two problems here, although they might have the same cause.

I created #27 to handle the error you encountered, which is caused because the function detection does not understand interface function signatures.

The other issue is that the fixture you provided somehow doesn't trigger the "it's an interface" detector. Taking a look at that now.

**Comment by sirbrillig** [comment]
#29 is the second issue.
