### ISSUE TITLE
Check for explicit `use` when referencing functions and constants

### ISSUE THREAD

**Issue by sirbrillig** [sirbrillig/phpcs-neutron-standard#45]
Check for consistent use statements, perhaps excluding namespace imports in favor of explicitly mentioning each function/const/etc (like eslint-plugin-imports's import/no-namespace).

Props @stuwest for the idea.

**Comment by sirbrillig** [comment]
Fixed by [ImportDetection](https://github.com/sirbrillig/phpcs-import-detection).

**Comment by Hywan** [comment]
:+1:
