### ISSUE TITLE
`RequireImports.Import` with `use const`

### ISSUE THREAD

**Issue by Hywan** [sirbrillig/phpcs-neutron-standard#72]
Hello,

The following code:

```php
use A\{B, C};

echo C;
```

will throw an error from `ImportDetection.Imports.RequireImports.Import` saying the constant `C` is unused, while it is :-).

Thanks for the tool!

**Comment by sirbrillig** [comment]
Thanks for the report!

Note: this is an issue for https://github.com/sirbrillig/phpcs-import-detection

However, I've been unable to reproduce the issue. I created a branch here to try to find it: https://github.com/sirbrillig/phpcs-import-detection/pull/23

Using that as a base, can you create a test case that fails?

**Comment by sirbrillig** [comment]
I also tried a simple manual test, and it looks correct to me (it only finds that `B` is unused):

```
user@dev~/public_html$ cat testConstants.php
<?php
use A\{B, C};

echo C;
user@dev:~/public_html$ phpcs --standard=ImportDetection testConstants.php

FILE: ~/public_html/testConstants.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 2 | WARNING | Found unused symbol 'A\B'.
----------------------------------------------------------------------
```

**Comment by Hywan** [comment]
Then, can you check D21704-code please?

**Comment by sirbrillig** [comment]
In that example, the code actually looks like this:

```php
use const A\{
  B, 
  C,
};

echo C;
```

That is failing because in PHP, grouped import statements cannot have a trailing comma on the final symbol. If you run `php -l` on that file, you'll get an error: `Parse error: syntax error, unexpected '}', expecting identifier (T_STRING)`.

If you remove the trailing comma, so it looks like the following, it should work.

```php
use const A\{
  B, 
  C
};

echo C;
```

**Comment by sirbrillig** [comment]
Oh, It looks like PHP 7.2 [might have added support for a trailing comma](https://wiki.php.net/rfc/list-syntax-trailing-commas). I created [an issue](https://github.com/sirbrillig/phpcs-import-detection/issues/24) to track that, but in any case, the PHP we can use in the diff you mentioned is PHP 7.1 only.
