### ISSUE TITLE
Disable Generic.Arrays.DisallowShortArraySyntax.Found

### ISSUE THREAD

**Issue by johnbillion** [sirbrillig/phpcs-neutron-standard#81]
When using Neutron with WordPress-Extra, you can't use short array syntax because WordPress-Extra disallows it (`Generic.Arrays.DisallowShortArraySyntax.Found`) but you also can't use long array syntax because Neutron disallows it (`NeutronStandard.Arrays.DisallowLongformArray.LongformArray`).

Is it possible for Neutron to exclude `Generic.Arrays.DisallowShortArraySyntax.Found` by default so it doesn't need to be excluded on a per-project basis when used in conjunction with WordPress-Extra?

**Comment by sirbrillig** [comment]
This was actually exactly the reason for creating [phpcs-neutron-ruleset](https://github.com/Automattic/phpcs-neutron-ruleset/) which combines NeutronStandard with WordPress but disables things that conflict.

**Comment by johnbillion** [comment]
Cheers, I'll give that a try.
